"""Extraction prompt templates for fact distillation."""

from __future__ import annotations

EXTRACTION_PROMPT = (
    "You convert a chat conversation into atomic memory facts about the USER, for later "
    "question-answering. RECALL IS CRITICAL: it is better to keep a detail than to drop it.\n"
    "The conversation turns are numbered [T0], [T1], ...\n"
    "Output one fact per line in EXACTLY this format:\n"
    "  <turn_index> | <atomic fact>\n"
    "where <turn_index> is the number of the SINGLE turn the fact comes from.\n"
    "Rules:\n"
    "- Write facts about the user: their life, preferences, plans, events, possessions, "
    "decisions, relationships, habits, opinions, and any concrete details they state or that "
    "are established about them (including specifics the user adopts from the assistant, e.g. "
    "a recommended product/resource the user accepts).\n"
    "- Each fact is a short, self-contained declarative sentence. Resolve ALL pronouns and "
    "references using the surrounding turns (never write 'it'/'they'/'the one' — name it).\n"
    "- PRESERVE EVERY CONCRETE SPECIFIC VERBATIM: proper names (people, brands, stores, places, "
    "apps, products), exact numbers/quantities, prices, and any dates or relative-time phrases. "
    "Never generalize a specific away (write 'Target', not 'a store').\n"
    "- Keep calendar dates at the finest granularity present in the source: if a day is known "
    "(e.g. April 2, 2024-04-02), write that day — do not coarsen to month-only ('April 2024'). "
    "If only a month/year is stated, keep that coarser form.\n"
    "- Keep one fact per distinct detail; do not merge multiple specifics into a vague summary.\n"
    "- Skip ONLY the assistant's generic boilerplate advice and general world knowledge.\n"
    "- Do NOT invent facts unsupported by the conversation.\n"
    "- If there are genuinely no user facts, output exactly: NONE\n\n"
    "Conversation (occurred on {date}):\n{transcript}\n\n"
    "Facts (one 'index | fact' per line):"
)

DOCUMENT_EXTRACTION_PROMPT = (
    "You convert source content into atomic memory facts for later question-answering. The "
    "content may be a document, notes, records, or a chat between one or more NAMED people "
    "(e.g. a WhatsApp/group-chat export where each message reads 'Name: text'). RECALL IS "
    "CRITICAL: it is better to keep a detail than to drop it.\n"
    "The content is split into numbered passages [T0], [T1], ... (for chats, one passage per "
    "message).\n"
    "Output one fact per line in EXACTLY this format:\n"
    "  <turn_index> | <atomic fact>\n"
    "where <turn_index> is the number of the SINGLE passage the fact comes from.\n"
    "Rules:\n"
    "- Write facts about the people, organizations, events, plans, decisions, places, and "
    "things described: who said/did/decided/planned what, when, where, and with whom, plus "
    "any concrete details stated (possessions, preferences, relationships, opinions, "
    "quantities, outcomes).\n"
    "- ATTRIBUTE EVERY STATEMENT TO ITS NAMED SOURCE: in chats, make the sender's name the "
    "subject of the fact (e.g. 'Zak said he will arrive at 19:00', 'Gaia proposed meeting at "
    "the beach on Saturday') — NEVER write 'the user', 'a member', or 'someone'. In "
    "documents, attribute each claim to the named person or entity it is about.\n"
    "- Each fact is a short, self-contained declarative sentence. Resolve ALL pronouns and "
    "references using the surrounding passages (never write 'it'/'they'/'the one' — name it).\n"
    "- PRESERVE EVERY CONCRETE SPECIFIC VERBATIM: proper names (people, brands, stores, places, "
    "apps, products), exact numbers/quantities, prices, times, and any dates or relative-time "
    "phrases. Never generalize a specific away (write 'Target', not 'a store').\n"
    "- Keep calendar dates at the finest granularity present: day when known "
    "(2024-04-02 / April 2), not month-only, unless the source only gives a month.\n"
    "- Keep one fact per distinct detail; do not merge multiple specifics into a vague summary.\n"
    "- Skip chat-app boilerplate and media placeholders (e.g. 'image omitted', 'sticker "
    "omitted', 'Messages and calls are end-to-end encrypted') — they are not facts.\n"
    "- Do NOT invent facts unsupported by the content.\n"
    "- Only if the content is truly contentless (pure boilerplate/placeholders), output "
    "exactly: NONE\n\n"
    "Content (dated {date}):\n{transcript}\n\n"
    "Facts (one 'index | fact' per line):"
)

NAMED_EXTRACTION_PROMPT = (
    "You convert a chat conversation into atomic memory facts about {subject}, the person "
    "whose memory this is, for later question-answering. RECALL IS CRITICAL: it is better to "
    "keep a detail than to drop it.\n"
    "The conversation turns are numbered [T0], [T1], ...\n"
    "Output one fact per line in EXACTLY this format:\n"
    "  <turn_index> | <atomic fact>\n"
    "where <turn_index> is the number of the SINGLE turn the fact comes from.\n"
    "Rules:\n"
    "- Write facts about {subject}: their life, preferences, plans, events, possessions, "
    "decisions, relationships, habits, opinions, and any concrete details about them (including "
    "specifics {subject} adopts from the assistant). Use the NAME '{subject}' as the subject of "
    "each fact (e.g. '{subject} prefers...'), NEVER the generic phrase 'the user'.\n"
    "- ATTRIBUTION IS CRITICAL: only attribute an email address, phone number, employer, title, "
    "or identity to {subject} when it is explicitly {subject}'s OWN. When a detail belongs to "
    "someone else (a contact, attendee, colleague, family member), name THAT person instead "
    "(e.g. 'Patricia's email is pjorda@sgfo.com'), and never say it is {subject}'s.\n"
    "- Each fact is a short, self-contained declarative sentence. Resolve ALL pronouns and "
    "references using the surrounding turns (never write 'it'/'they'/'the one' — name it).\n"
    "- PRESERVE EVERY CONCRETE SPECIFIC VERBATIM: proper names (people, brands, stores, places, "
    "apps, products), exact numbers/quantities, prices, and any dates or relative-time phrases. "
    "Never generalize a specific away (write 'Target', not 'a store').\n"
    "- Keep one fact per distinct detail; do not merge multiple specifics into a vague summary.\n"
    "- Skip ONLY the assistant's generic boilerplate advice and general world knowledge.\n"
    "- Do NOT invent facts unsupported by the conversation.\n"
    "- If there are genuinely no facts about {subject}, output exactly: NONE\n\n"
    "Conversation (occurred on {date}):\n{transcript}\n\n"
    "Facts (one 'index | fact' per line):"
)
